server {
    server_name angriffe.azamatsysteme.fun;

    root /home/claude/attack-dashboard;
    index index.html;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    location = /myip {
        default_type text/plain;
        add_header Cache-Control "no-store";
        return 200 "$remote_addr";
    }

    location / {
        try_files $uri $uri/ =404;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/angriffe.azamatsysteme.fun/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/angriffe.azamatsysteme.fun/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = angriffe.azamatsysteme.fun) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name angriffe.azamatsysteme.fun;
    return 404; # managed by Certbot


}
